steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        docker build -t gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE} .
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta run deploy ${_CLOUD_RUN_SERVICE} \
        --allow-unauthenticated \
        --image gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE} \
        --region us-central1 \
        --platform managed \
        --memory 256Mi \
        --update-env-vars APP_DEBUG=${_APP_DEBUG}
images:
  - gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}
options:
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _APP_DEBUG: 'true'


