adımlar:
  - isim: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}', '.']
  - isim: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}']
  - isim: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta', 
      'run', 
      'deploy', 
      '--allow-unauthenticated', 
      '${_CLOUD_RUN_SERVICE}', 
      '--image', 
      'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}', 
      '--region', 
      'us-central1', 
      '--platform', 
      'managed', 
      '--memory', 
      '256Mi', 
      '--update-env-vars', 
      'APP_DEBUG=${_APP_DEBUG}'
    ]

görüntüler:
  - 'gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE}'

seçenekler:
  ikame_seçimi: 'ALLOW_LOOSE'

ikameler:
  _APP_DEBUG: 'doğru'

